development:
  adapter: postgresql
  encoding: unicode
  database: taxi_service_development
  pool: 5
  username: taxi_service
  password: 354293sas
test:
  adapter: postgresql
  encoding: unicode
  database: taxi_service_test
  pool: 5
  username: taxi_service
  password: 354293sas